menu:
    Articles: /
    Archive: /archives/
    GitHub: https://github.com/imuxin/blog
    Contribute: 2019/09/29/contribute/
    About: /2019/09/15/About/

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2019
